<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <RootNamespace>com.ih.util.generic</RootNamespace>
    <Title>IH - Generic - Util</Title>
    <Copyright>Library with Commons Utilities for .NET Rest APIs</Copyright>
    <Company>IH</Company>
    <Authors>Irineu Hübner (irineush@gmail.com)</Authors>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="com.ih.util.custom.errors" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.Abstractions" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="LogFile\Service\ILogFileService.cs" />
    <Compile Remove="InternetPublicAddress\Service\IIpGeolocationService.cs" />
  </ItemGroup>
</Project>